import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the `courses` docs instance (see docusaurus.config.ts).
// Autogenerated from the folder structure under `courses/`:
//   - each course is a top-level category folder with a `_category_.json`
//   - page order comes from each page's `sidebar_position` frontmatter
const sidebars: SidebarsConfig = {
  coursesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
